---
openapi: 3.0.3
info:
  title: ''
  version: ''
paths:
  /masuk:
    get:
      tags:
        - publik
      description: |
        Jika token tak diberikan, mendapatkan token baru untuk masuk ke dalam sistem.<br/>
        Jika token diberikan, mendapatkan rincian sesi, seperti hak akses dan acara terpilih.
      security:
        - token: []
        - cookie: []
      responses:
        200:
          description: Sukses mendapatkan token baru.
          content:
            application/json:
              example: {
                "token": "qwer24k6lm8asdfghj02xcvbnm",
                "sesi": {}
              }
        200 (a):
          description: Sukses mendapatkan rincian sesi menurut token.
          content:
            application/json:
              example: {
                "token": "qwer24k6lm8asdfghj02xcvbnm",
                "sesi": {
                  "id": 8,
                  "pengguna": "TBOXCREW0001",
                  "nama": "Simera T01",
                  "pin_belum_diganti": false,
                  "peran": "petugas_penukaran",
                  "akses": [ 4, 7, 6, 21 ],
                  "id_grup": 0,
                  "grup": "",
                  "id_mitra": 0,
                  "mitra": "",
                  "id_acara": 1,
                  "acara": "Acara Uji Coba",
                  "bahasa": "id",
                  "gaya": "bahari_hijau"
                }
              }
        401:
          description: Token tidak sah.
          content:
            text/html:
              example: 'WWW-Authenticate: Bearer'
      
    post:
      tags:
        - publik
      description: |
        Masuk ke dalam sistem. Bisa menggunakan ID pengguna dan PIN, atau dengan kartu akses.
      security:
        - token: []
        - cookie: []
      requestBody:
        content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  i:
                    type: string
                    description: |
                      ID pengguna.<br/>
                      Kirimkan bersamaan dengan `p`. Jangan sertakan `k`.
                  p:
                    type: number
                    description: |
                      PIN.<br/>
                      Kirimkan bersamaan dengan `i`. Jangan sertakan `k`.
                  k:
                    type: string
                    description: |
                      Hasil pindai kode QR atau NFC kartu akses.<br/>
                      Jika `k` dikirimkan (meski dengan nilai kosong), `i` dan `p` akan diabaikan.
      responses:
        302:
          $ref: openapi.yaml#/components/responses/302
        422:
          allOf:
            - $ref: openapi.yaml#/components/responses/422
            - content:
                application/json:
                  example: {
                    "status": "dialihkan",
                    "jenis": "galat",
                    "pesan": "Akun Anda diblokir, silakan hubungi pengurus",
                    "url": "/masuk"
                  }
  
  /bahasa:
    get:
      tags:
        - publik
      description: |
        Mendapatkan daftar bahasa, dan bahasa terpilih berikut daftar terjemahannya.
      security:
        - token: []
        - cookie: []
      responses:
        200:
          description: Sukses.
          content:
            application/json:
              example: {
                "pilihan": [
                  [ "en", "English" ],
                  [ "id", "Bahasa Indonesia" ]
                ],
                "bahasa": "id",
                "terjemahan": {
                  "nama_bahasa": "Bahasa Indonesia",
                  "bahasa": "Bahasa",
                  "pemisah_label": ": ",
                  "pemisah_butir": ", ",
                  "pemisah_ribuan": ".",
                  "pemisah_desimal": ",",
                  "tanda_persen": "%",
                  "tanda_kosong": "-",
                  "validasi_semua_bidang": "Semua bidang",
                  "validasi_diisi": "{0} harus diisi",
                  "validasi_opsi": "{0} harus dipilih",
                  "validasi_angka": "{0} harus berupa angka",
                  "validasi_bulat_positif": "{0} harus berupa bilangan bulat positif",
                  "validasi_tanggal": "{0} harus berupa tanggal yang benar",
                  "validasi_surel": "{0} harus berupa alamat yang benar",
                }
              }
    post:
      tags:
        - publik
      description: |
        Mengganti bahasa terpilih.
      security:
        - token: []
        - cookie: []
      requestBody:
        content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  kode:
                    type: string
                    description: Kode bahasa.
      responses:
        302:
          $ref: openapi.yaml#/components/responses/302
